name: Replace String in Special Folder

on:
  push:
    branches:
      - develop  # Modify this according to your branch name
    paths:
      - 'docs/**/*.md'

jobs:
  replace_string:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3


    - name: Replace string
      run: |
        find ./docs -type f -name "*.md" -exec sed -i 's|/docs/public/images|/images|g' {} \;


    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Replace old_string with new_string"
        git push